title:              Terryinfcco Blog
email:              terryinclmich@hotmail.com
description:        My Personal Blog of Technology Findings. For my own personal use, but if someone else finds it useful all the better.
author:             Terryinfcco
baseurl:            "/clean-blog-jekyll"
url:                "https://github.com/terryinfcco.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
